// Next Components
import Head from 'next/head';

// Components
import Layout from '../../components/Layout';
import SpotifyItem from '../../components/SpotifyItem';
import SpotifyItemSkeleton from '../../components/SpotifyItemSkeleton';
import Table from '../../components/Table';

// Styles
import { container, itemContainer } from '../../styles/Playlist.module.css';
import {
	textSm,
	textMd,
	textWhite,
	textBold,
	textXxl,
	mt0,
} from '../../styles/utils.module.css';

// NextAuth
import { useSession } from 'next-auth/react';

// Hooks
import { useRouter } from 'next/router';

// Axios
import axios from 'axios';

// SWR
import useSWR from 'swr';
const fetcher = async (...args) =>
	await axios.get(...args).then((res) => res.data);

export default function Playlist() {
	const { data: session, status } = useSession();
	const router = useRouter();
	const { playlist: id, name } = router.query;
	const { data: playlistData, error: playlistDataError } = useSWR(
		id ? `../api/getPlaylistItems?id=${id}` : null,
		fetcher,
		{
			revalidateOnFocus: false,
			revalidateIfStale: false,
		}
	);
	console.log(playlistData);
	if (!session) {
		return (
			<>
				<Layout>
					<div className={container}>
						<h1 className={`${textMd} ${textWhite} ${textBold}`}>
							Please Sign In
						</h1>
					</div>
				</Layout>
			</>
		);
	}
	if (session && playlistData) {
		return (
			<>
				<Head>
					<title>{`Next Spotify | ${name}`}</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<Layout>
					<div className={container}>
						<p className={`${textWhite} ${textBold} ${textSm}`}>PLAYLIST</p>
						<p className={`${textWhite} ${textBold} ${mt0} ${textXxl}`}>
							{name}
						</p>
						<hr />
						<Table data={playlistData.items}></Table>
					</div>
				</Layout>
			</>
		);
	}
	return (
		<>
			<Head>
				<title>{`Next Spotify | ${name}`}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<div className={container}>
					<p className={`${textWhite} ${textBold} ${textSm}`}>PLAYLIST</p>
					<p className={`${textWhite} ${textBold} ${textXxl} ${mt0}`}>{name}</p>
					<div className={itemContainer}>
						<p className={`${textWhite} ${textBold}`}>Loading...</p>
					</div>
				</div>
			</Layout>
		</>
	);
}
