// Next Components
import Head from 'next/head';
import Link from 'next/link';

// Components
import Layout from '../../components/Layout';
import SpotifyItem from '../../components/SpotifyItem';
import SpotifyItemSkeleton from '../../components/SpotifyItemSkeleton';

// Styles
import { container, itemContainer } from './Category.module.css';
import {
	textMd,
	textWhite,
	textBold,
	textXxl,
} from '../../styles/utils.module.css';

// NextAuth
import { useSession } from 'next-auth/react';

// Hooks
import { useRouter } from 'next/router';

// Axios
import axios from 'axios';

// SWR
import useSWR from 'swr';
const fetcher = async (...args) =>
	await axios.get(...args).then((res) => res.data);

export default function Category() {
	const { data: session, status } = useSession();
	const router = useRouter();
	const { category, genre } = router.query;
	const { data: playlistData, error: playlistDataError } = useSWR(
		category ? `../api/getCategoryPlaylist?category=${category}` : null,
		fetcher,
		{
			revalidateOnFocus: false,
			revalidateIfStale: false,
		}
	);
	// console.log(playlistData);
	if (!session) {
		return (
			<>
				<Layout>
					<div className={container}>
						<h1 className={`${textMd} ${textWhite} ${textBold}`}>
							Please Sign In
						</h1>
					</div>
				</Layout>
			</>
		);
	}
	if (session && playlistData) {
		return (
			<>
				<Head>
					<title>{`Next Spotify | ${genre}`}</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<Layout>
					<div className={container}>
						<p className={`${textWhite} ${textBold} ${textXxl}`}>{genre}</p>
						<div className={itemContainer}>
							{playlistData.playlists.items.map((playlistItem, i) => {
								return (
									<Link
										href={{
											pathname: `/playlist/${playlistItem.id}`,
											query: { name: playlistItem.name },
										}}
										key={`playlist/${i}`}
									>
										<a>
											<SpotifyItem data={playlistItem}></SpotifyItem>
										</a>
									</Link>
								);
							})}
						</div>
					</div>
				</Layout>
			</>
		);
	}
	return (
		<>
			<Head>
				<title>{`Next Spotify | ${genre}`}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<div className={container}>
					<p className={`${textWhite} ${textBold} ${textXxl}`}>{genre}</p>
					<div className={itemContainer}>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
						<SpotifyItemSkeleton></SpotifyItemSkeleton>
					</div>
				</div>
			</Layout>
		</>
	);
}
