// Next Components
import Head from 'next/head';

// Components
import Layout from '../../components/Layout';

// Styles
import { container } from '../../styles/Search.module.css';
import { textMd, textWhite, textBold } from '../../styles/utils.module.css';

// NextAuth
import { useSession } from 'next-auth/react';

// Hooks
import { useRouter } from 'next/router';

export default function Category() {
	const { data: session, status } = useSession();
	const router = useRouter();
	const { category } = router.query;
	if (!session) {
		return (
			<>
				<Layout>
					<div className={container}>
						<h1 className={`${textMd} ${textWhite} ${textBold}`}>
							Please Sign In
						</h1>
					</div>
				</Layout>
			</>
		);
	}
	return (
		<>
			<Head>
				<title>Next Spotify | Search</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<div className={container}>
					<p className={`${textWhite} ${textBold} ${textMd}`}>{category}</p>
				</div>
			</Layout>
		</>
	);
}
