// Next Components
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/Layout';

// Hooks

// Services

// Styles
import styles from '../styles/Home.module.css';

// NextAuth
import { useSession } from 'next-auth/react';

export default function Home() {
	const { data: session, status } = useSession();
	if (status === 'authenticated') {
		return (
			<>
				<Head>
					<title>Next Spotify</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>

				<Layout>
					<h1>Signed in as {session.user.name}</h1>
				</Layout>
			</>
		);
	}
	return (
		<>
			<Layout>
				<h1>Please Sign In</h1>
			</Layout>
		</>
	);
}
