// Next Components
import Head from 'next/head';

// Components
import Layout from '../components/Layout';
import PlaylistItem from '../components/PlaylistItem';

// Hooks
import { useEffect, useState } from 'react';

// Styles
import {
	container,
	tracksContainer,
	playlistGrid,
} from '../styles/Library.module.css';
import { textMd, textWhite, textBold } from '../styles/utils.module.css';

// NextAuth
import { useSession } from 'next-auth/react';

// Axios
import axios from 'axios';

// SWR

import useSWR from 'swr';
const fetcher = async (...args) =>
	await axios.get(...args).then((res) => res.data);

export default function Library() {
	const { data: session, status } = useSession();
	const { data: playlistData, error: playlistError } = useSWR(
		'/api/getPlaylists',
		fetcher,
		{
			revalidateOnFocus: false,
			revalidateIfStale: false,
		}
	);
	console.log(playlistData);
	if (session) {
		if (!playlistData) {
			return (
				<Layout>
					<div className={container}>
						<p className={`${textMd} ${textWhite} ${textBold}`}>Loading...</p>
					</div>
				</Layout>
			);
		}
		return (
			<>
				<Head>
					<title>Next Spotify | My Library</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>

				<Layout>
					<div className={container}>
						<p className={`${textWhite} ${textBold} ${textMd}`}>My Library</p>
						<div className={playlistGrid}>
							{playlistData.items.map((playlist) => {
								return <PlaylistItem key={playlist.id} data={playlist} />;
							})}
						</div>
					</div>
				</Layout>
			</>
		);
	}
	return (
		<>
			<Layout>
				<div className={container}>
					<h1 className={`${textMd} ${textWhite} ${textBold}`}>
						Please Sign In
					</h1>
				</div>
			</Layout>
		</>
	);
}
